"""
Export models/activity_classifier.pkl (trained by train_activity_classifier.py) to a
C header, following the same pattern already used by firmware/ble/classifier.h etc.
(nested if/else on the sklearn tree's own splits) -- this project does NOT use TFLite
Micro despite what the README roadmap says; the existing classifier.h files are
hand-generated-looking nested if/else, so this matches established convention instead
of introducing a new deployment path.

The existing classifier.h is a DIFFERENT (binary, 3-feature) model actively used by 3
firmware variants -- this script writes a NEW file, does not touch classifier.h, since
swapping in a 5-class model is a firmware integration decision for a human to make.

Usage:
    python scripts/train/export_classifier_to_c.py
"""
import joblib
import numpy as np

IN_PATH = "models/activity_classifier.pkl"
OUT_PATH = "firmware/ble/activity_classifier_5class.h"


def node_to_c(tree, node, feature_names, class_names, indent):
    if tree.feature[node] == -2:  # leaf
        class_idx = int(np.argmax(tree.value[node]))
        return f"{indent}return {class_idx}; // {class_names[class_idx]}\n"
    fname = feature_names[tree.feature[node]]
    thresh = tree.threshold[node]
    left = node_to_c(tree, tree.children_left[node], feature_names, class_names, indent + "    ")
    right = node_to_c(tree, tree.children_right[node], feature_names, class_names, indent + "    ")
    return f"{indent}if ({fname} <= {thresh:.4f}f) {{\n{left}{indent}}} else {{\n{right}{indent}}}\n"


def main():
    bundle = joblib.load(IN_PATH)
    model, features, classes = bundle["model"], bundle["features"], bundle["classes"]
    tree = model.tree_

    params = ", ".join(f"float {f}" for f in features)
    body = node_to_c(tree, 0, features, classes, "    ")
    class_comment = "\n".join(f" *   {i} = {c}" for i, c in enumerate(classes))

    header = f"""#ifndef ACTIVITY_CLASSIFIER_5CLASS_H
#define ACTIVITY_CLASSIFIER_5CLASS_H

/* Generated by export_classifier_to_c.py from {IN_PATH} -- do not hand-edit, re-run
 * train_activity_classifier.py + this script instead.
 * LOGO-CV mean accuracy: 0.547 (see CHANGELOG.md 2026-07-28) -- lying/sitting/standing
 * are heavily confused (root-caused: magnitude-only features can't carry orientation
 * info, see project memory bug-1). walking/running are reliable (recall 0.64/0.77).
 * Class codes:
{class_comment}
 */

int classifyActivity5class({params}) {{
{body}}}

#endif
"""
    with open(OUT_PATH, "w") as fh:
        fh.write(header)
    print(f"Wrote {OUT_PATH} ({tree.node_count} nodes, {len(features)} features, {len(classes)} classes)")


if __name__ == "__main__":
    main()
