#ifndef ACTIVITY_CLASSIFIER_5CLASS_H
#define ACTIVITY_CLASSIFIER_5CLASS_H

/* Generated by export_classifier_to_c.py from models/activity_classifier.pkl -- do not hand-edit, re-run
 * train_activity_classifier.py + this script instead.
 * LOGO-CV mean accuracy: 0.547 (see CHANGELOG.md 2026-07-28) -- lying/sitting/standing
 * are heavily confused (root-caused: magnitude-only features can't carry orientation
 * info, see project memory bug-1). walking/running are reliable (recall 0.64/0.77).
 * Class codes:
 *   0 = lying
 *   1 = running
 *   2 = sitting
 *   3 = standing
 *   4 = walking
 */

int classifyActivity5class(float mean_mag, float std_mag, float peak_rel, float peak_max) {
    if (std_mag <= 685.4000f) {
        if (std_mag <= 188.7500f) {
            if (mean_mag <= 1844.8500f) {
                if (mean_mag <= 1809.4500f) {
                    if (mean_mag <= 1786.2500f) {
                        return 2; // sitting
                    } else {
                        return 3; // standing
                    }
                } else {
                    if (mean_mag <= 1831.0500f) {
                        return 2; // sitting
                    } else {
                        return 2; // sitting
                    }
                }
            } else {
                if (mean_mag <= 2099.9000f) {
                    if (mean_mag <= 1871.8500f) {
                        return 0; // lying
                    } else {
                        return 3; // standing
                    }
                } else {
                    if (mean_mag <= 2171.4500f) {
                        return 0; // lying
                    } else {
                        return 0; // lying
                    }
                }
            }
        } else {
            if (mean_mag <= 1907.0500f) {
                if (mean_mag <= 1878.0500f) {
                    if (std_mag <= 224.9000f) {
                        return 2; // sitting
                    } else {
                        return 1; // running
                    }
                } else {
                    if (peak_rel <= 1.6050f) {
                        return 4; // walking
                    } else {
                        return 1; // running
                    }
                }
            } else {
                if (peak_max <= 4069.1000f) {
                    if (mean_mag <= 2144.7500f) {
                        return 4; // walking
                    } else {
                        return 0; // lying
                    }
                } else {
                    if (mean_mag <= 1963.1500f) {
                        return 1; // running
                    } else {
                        return 0; // lying
                    }
                }
            }
        }
    } else {
        if (peak_rel <= 1.7250f) {
            if (mean_mag <= 2148.7500f) {
                return 1; // running
            } else {
                if (peak_rel <= 1.6550f) {
                    if (peak_max <= 3596.3501f) {
                        return 4; // walking
                    } else {
                        return 4; // walking
                    }
                } else {
                    if (mean_mag <= 2478.2001f) {
                        return 4; // walking
                    } else {
                        return 1; // running
                    }
                }
            }
        } else {
            if (peak_rel <= 4.2200f) {
                if (std_mag <= 690.1500f) {
                    return 1; // running
                } else {
                    if (peak_max <= 3706.2001f) {
                        return 1; // running
                    } else {
                        return 1; // running
                    }
                }
            } else {
                if (peak_max <= 19722.2002f) {
                    return 2; // sitting
                } else {
                    return 1; // running
                }
            }
        }
    }
}

#endif
